# Generated by Django 6.1.2 on 2026-10-07 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EspecieProtegida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cientifico', models.CharField(db_index=True, max_length=200, unique=True)),
                ('nombre_comun', models.CharField(blank=True, max_length=200, null=True)),
                ('categoria', models.CharField(choices=[('CR', 'En Peligro Crítico'), ('EN', 'En Peligro'), ('VU', 'Vulnerable'), ('NT', 'Casi Amenazada'), ('LC', 'Preocupación Menor'), ('MN', 'Monumento Natural')], default='LC', max_length=2)),
                ('origen', models.CharField(choices=[('E', 'Endémica'), ('N', 'Nativa'), ('I', 'Introducida')], default='N', max_length=1)),
                ('decreto', models.CharField(blank=True, help_text='Ej: DS 13/1995 MINAGRI', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Especie Protegida',
                'verbose_name_plural': 'Especies Protegidas',
            },
        ),
    ]
